### DISCUSSION TITLE
`pdk rake` and/or ability to create pdk aliases within a repo (like in git)

### DISCUSSION THREAD

**Discussion by jay7x** [puppetlabs/pdk#1206] [Feature Request]
Hello!

I'm a bit tired to type `pdk bundle exec rake` every time I need to run some rake task within a PDK-managed repository.. So I'd like to have `pdk rake` alias for this. Though going further someone may ask for `pdk rspec` etc.. so to prevent pandora box from being opened maybe it's better to implement general solution like "pdk aliases". This should work in similar way as it's done in `git` e.g. I.e. one can use PDK configuration to define aliases globally/per-user/per-repo (in same way as PDK config is read IIRC).

Why not shell alias? Because you should configure the alias yourself in your shell.. while PDK alias can be defined in a repository. So your end-user might start using it w/o need to configure any shell aliases.

Config might look like this:

```yaml
alias:
  rake: bundle exec rake
  rspec: bundle exec rspec
```

Though maybe I'd even prefer this to be able to execute 3rd party apps.. and then config should looks like this (just random things out of my head):

```yaml
commands:
  rake: pdk bundle exec rake
  rspec: pdk bundle exec rspec
  validate-plan: "pdk bundle exec puppet parser validate --tasks plans/**/*.pp"
  validate-yamllint: pipenv exec yamllint
  test-acceptance: pdk bundle exec rake beaker:all
```

Ideally I'd prefer to have ability to define subcommands as well.. e.g. to define `validate-yamllint` above as the `yamllint` subcommand of the `validate` command. Though one shouldn't be able to override any existing command so maybe it is too much.
