### ISSUE TITLE
Cannot override module Hiera 5 config for unit tests

### ISSUE THREAD

**Issue by ragnarkon** [puppetlabs/pdk#487]
There appears to be no way to override the module layer Hiera 5 configuration in for unit tests. Having the ability to override the Hiera 5 module layer configuration would extremely helpful, particularly when running unit tests on eyaml data where the developer (or CI pipeline) may not have access to the public/private keys.

Furthermore, if the developer *did* have access to the public/private keys, the hiera-eyaml gem is not included in the Gemfile by default, causing unit tests to fail.  (Admittedly, an easy problem for the user to fix themselves.)

**Current Behavior**
```
failed: rspec: ./spec/classes/init_spec.rb:9: error during compilation: Evaluation Error:
Error while evaluating a Function Call, Function Load Error for function
'eyaml_lookup_key': Lookup using eyaml lookup_key function is only supported when
the hiera_eyaml library is present (line: 3, column: 1)
```

---

Example `./hiera5.yaml` that should be overwritten:
```yaml
version: 5
defaults:
  datadir: data
  lookup_key: eyaml_lookup_key
  options:
    pkcs7_private_key: /etc/puppetlabs/code/keys/private_key.pkcs7.pem
    pkcs7_public_key: /etc/puppetlabs/code/keys/public_key.pkcs7.pem
hierarchy:

  - name: "Common Eyaml"
    path: "common.eyaml"
```

`./spec/fixtures/hiera/hiera.yaml` file used for unit tests:
```yaml
version: 5
defaults:
  datadir: spec/fixtures/hiera/data
  data_hash: yaml_data
hierarchy:

  - name: "Common Eyaml"
    path: "common.eyaml"
```

`./spec/spec_helper.rb`:
```ruby
# ...
default_fixtures_path = File.expand_path(File.join(File.dirname(__FILE__), 'fixtures'))

RSpec.configure do |c|
  c.default_facts = default_facts
  c.after(:suite) do
    RSpec::Puppet::Coverage.report!
  end
  # Hiera config file for unit tests
  c.hiera_config = File.join(default_fixtures_path, 'hiera/hiera.yaml')
end
```
