### ISSUE TITLE
pdk validate reports error on is_to_s

### ISSUE THREAD

**Issue by myMarck** [puppetlabs/pdk#642]
**Describe the bug**
If your type has a property that implements is_to_s pdk valiate 
pdk validate 
convention: rubocop: lib/puppet/type/bmc_user.rb:26:9: Style/PredicateName: Rename `is_to_s` to `to_s?`.
**To Reproduce**
Create a type with a property like this

  newproperty(:password) do
    desc 'Password used to login'

    def should_to_s(_value)
      '<secret>'
    end
    def is_to_s(_value)
      '<secret>'
    end
  end

The simplest sequence of steps you have discovered which triggers the bug.
pdk validte

**Expected behavior**

**Additional context**
pdk 1.9.1
A workaround is to implement change_to_s

**Comment by DavidS** [comment]
We can add `is_to_s` to the whitelist in the [default configs](https://github.com/puppetlabs/pdk-templates/blob/bba9ac3cc7649fcd4b8ecdfbad1590999df8b9a9/config_defaults.yml#L125). See this example for syntax:
```
david@davids:~/git/puppetlabs-motd$ pdk bundle exec rubocop --show-cops Style/PredicateName
pdk (INFO): Using Ruby 2.5.3
pdk (INFO): Using Puppet 6.2.0
Style/PredicateName:
  Description: Check the names of predicate methods.
  StyleGuide: "#bool-methods-qmark"
  Enabled: true
  NamePrefix:
  - is_
  - has_
  - have_
  NamePrefixBlacklist:
  - is_
  - has_
  - have_
  NameWhitelist:
  - is_a?
  Exclude:
  - "/home/david/git/puppetlabs-motd/spec/**/*"


david@davids:~/git/puppetlabs-motd$ 
```

**Comment by scotje** [comment]
@myMarck can you try adding this following snippet to your module's `.sync.yml` file:

```
.rubocop.yml:
  default_configs:
    Style/PredicateName:
      NameWhitelist:
        - is_to_s
```

Then run `pdk update` and finally `pdk validate` to see if the warning goes away?
